// Item and recipe coverage missing from the original core-production subset.
// Recipe values are generated from the FactorioLab DSP game-resource dataset.
import type { Item, Recipe } from "./dsp-data.ts";

export const EXPANDED_ITEMS: Item[] = [
  { id: "log", name: "원목", en: "Log", category: "raw", glyph: "Lg", raw: true },
  { id: "plant_fuel", name: "식물 연료", en: "Plant Fuel", category: "raw", glyph: "Pf", raw: true },
  { id: "df_core_element", name: "코어 소자", en: "Core Element", category: "raw", glyph: "Ce", raw: true },

  { id: "critical_photon", name: "임계 광자", en: "Critical Photon", category: "component", glyph: "Cp" },
  { id: "df_strange_annihilation_fuel_rod", name: "기묘한 소멸 연료봉", en: "Strange Annihilation Fuel Rod", category: "fuel", glyph: "Sf" },

  { id: "thruster", name: "추진기", en: "Thruster", category: "logistics", glyph: "Th" },
  { id: "logistics_bot", name: "물류 봇", en: "Logistics Bot", category: "logistics", glyph: "Lb" },
  { id: "logistics_drone", name: "물류 드론", en: "Logistics Drone", category: "logistics", glyph: "Ld" },
  { id: "logistics_vessel", name: "성간 물류 운송선", en: "Interstellar Logistics Vessel", category: "logistics", glyph: "Lv" },
  { id: "space_warper", name: "공간 워퍼", en: "Space Warper", category: "logistics", glyph: "Sw" },
  { id: "foundation", name: "토대", en: "Foundation", category: "logistics", glyph: "Fd" },
  { id: "proliferator_1", name: "증산제 Mk.I", en: "Proliferator Mk.I", category: "logistics", glyph: "P1" },
  { id: "proliferator_2", name: "증산제 Mk.II", en: "Proliferator Mk.II", category: "logistics", glyph: "P2" },
  { id: "proliferator_3", name: "증산제 Mk.III", en: "Proliferator Mk.III", category: "logistics", glyph: "P3" },

  { id: "df_combustible_unit", name: "연소 유닛", en: "Combustible Unit", category: "combat", glyph: "Cu" },
  { id: "df_explosive_unit", name: "폭발 유닛", en: "Explosive Unit", category: "combat", glyph: "Eu" },
  { id: "df_crystal_explosive_unit", name: "결정 폭발 유닛", en: "Crystal Explosive Unit", category: "combat", glyph: "Ce" },
  { id: "df_magnum_ammo_box", name: "매그넘 탄약 상자", en: "Magnum Ammo Box", category: "combat", glyph: "Ma" },
  { id: "df_titanium_ammo_box", name: "티타늄 탄약 상자", en: "Titanium Ammo Box", category: "combat", glyph: "Ta" },
  { id: "df_superalloy_ammo_box", name: "초합금 탄약 상자", en: "Superalloy Ammo Box", category: "combat", glyph: "Sa" },
  { id: "df_shell_set", name: "포탄 세트", en: "Shell Set", category: "combat", glyph: "Ss" },
  { id: "df_high_explosive_shell_set", name: "고폭탄 세트", en: "High-Explosive Shell Set", category: "combat", glyph: "Hs" },
  { id: "df_crystal_shell_set", name: "결정 포탄 세트", en: "Crystal Shell Set", category: "combat", glyph: "Cs" },
  { id: "df_plasma_capsule", name: "플라즈마 캡슐", en: "Plasma Capsule", category: "combat", glyph: "Pc" },
  { id: "df_antimatter_capsule", name: "반물질 캡슐", en: "Antimatter Capsule", category: "combat", glyph: "Ac" },
  { id: "df_missile_set", name: "미사일 세트", en: "Missile Set", category: "combat", glyph: "Ms" },
  { id: "df_supersonic_missile_set", name: "초음속 미사일 세트", en: "Supersonic Missile Set", category: "combat", glyph: "Sm" },
  { id: "df_gravity_missile_set", name: "중력 미사일 세트", en: "Gravity Missile Set", category: "combat", glyph: "Gm" },
  { id: "df_jamming_capsule", name: "전파 방해 캡슐", en: "Jamming Capsule", category: "combat", glyph: "Jc" },
  { id: "df_suppressing_capsule", name: "억제 캡슐", en: "Suppressing Capsule", category: "combat", glyph: "Sc" },
  { id: "df_prototype", name: "프로토타입", en: "Prototype", category: "combat", glyph: "Pt" },
  { id: "df_precision_drone", name: "정밀 드론", en: "Precision Drone", category: "combat", glyph: "Pd" },
  { id: "df_attack_drone", name: "공격 드론", en: "Attack Drone", category: "combat", glyph: "Ad" },
  { id: "df_corvette", name: "코르벳함", en: "Corvette", category: "combat", glyph: "Cv" },
  { id: "df_destroyer", name: "구축함", en: "Destroyer", category: "combat", glyph: "Ds" },
];

export const EXPANDED_RECIPES: Recipe[] = [
  {
    id: "critical-photon",
    outputId: "critical_photon",
    outputQty: 6,
    timeSec: 60,
    facility: "ray_receiver",
    inputs: [],
    productive: false,
  },
  {
    id: "critical-photon-graviton",
    outputId: "critical_photon",
    outputQty: 12,
    timeSec: 60,
    facility: "ray_receiver",
    inputs: [{ itemId: "graviton_lens", qty: 0.1 }],
    alternate: true,
    productive: false,
  },
  { id: "df-strange-annihilation-fuel-rod", outputId: "df_strange_annihilation_fuel_rod", outputQty: 1, timeSec: 32, facility: "assembler", inputs: [{ itemId: "antimatter_fuel_rod", qty: 8 }, { itemId: "df_core_element", qty: 1 }, { itemId: "frame_material", qty: 1 }, { itemId: "strange_matter", qty: 2 }], productive: true },

  { id: "thruster", outputId: "thruster", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "copper_ingot", qty: 3 }, { itemId: "steel", qty: 2 }], productive: true },
  { id: "logistics-bot", outputId: "logistics_bot", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "df_engine", qty: 1 }, { itemId: "iron_ingot", qty: 2 }, { itemId: "processor", qty: 1 }], productive: true },
  { id: "logistics-drone", outputId: "logistics_drone", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "iron_ingot", qty: 5 }, { itemId: "processor", qty: 2 }, { itemId: "thruster", qty: 2 }], productive: true },
  { id: "logistics-vessel", outputId: "logistics_vessel", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "processor", qty: 10 }, { itemId: "reinforced_thruster", qty: 2 }, { itemId: "titanium_alloy", qty: 10 }], productive: true },
  { id: "space-warper", outputId: "space_warper", outputQty: 1, timeSec: 10, facility: "assembler", inputs: [{ itemId: "graviton_lens", qty: 1 }], productive: true },
  { id: "space-warper-advanced", outputId: "space_warper", outputQty: 8, timeSec: 10, facility: "assembler", inputs: [{ itemId: "gravity_matrix", qty: 1 }], alternate: true, productive: true },
  { id: "foundation", outputId: "foundation", outputQty: 1, timeSec: 1, facility: "assembler", inputs: [{ itemId: "steel", qty: 1 }, { itemId: "stone_brick", qty: 3 }], productive: true },
  { id: "proliferator-1", outputId: "proliferator_1", outputQty: 1, timeSec: 0.5, facility: "assembler", inputs: [{ itemId: "coal", qty: 1 }], productive: true },
  { id: "proliferator-2", outputId: "proliferator_2", outputQty: 1, timeSec: 1, facility: "assembler", inputs: [{ itemId: "diamond", qty: 1 }, { itemId: "proliferator_1", qty: 2 }], productive: true },
  { id: "proliferator-3", outputId: "proliferator_3", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "carbon_nanotube", qty: 1 }, { itemId: "proliferator_2", qty: 2 }], productive: true },

  { id: "df-combustible-unit", outputId: "df_combustible_unit", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "coal", qty: 3 }], productive: true },
  { id: "df-explosive-unit", outputId: "df_explosive_unit", outputQty: 2, timeSec: 6, facility: "chemical", inputs: [{ itemId: "df_combustible_unit", qty: 2 }, { itemId: "plastic", qty: 2 }, { itemId: "sulfuric_acid", qty: 1 }], productive: true },
  { id: "df-crystal-explosive-unit", outputId: "df_crystal_explosive_unit", outputQty: 8, timeSec: 24, facility: "chemical", inputs: [{ itemId: "casimir_crystal", qty: 1 }, { itemId: "crystal_silicon", qty: 8 }, { itemId: "df_explosive_unit", qty: 8 }], productive: true },
  { id: "df-magnum-ammo-box", outputId: "df_magnum_ammo_box", outputQty: 1, timeSec: 1, facility: "assembler", inputs: [{ itemId: "copper_ingot", qty: 3 }], productive: true },
  { id: "df-titanium-ammo-box", outputId: "df_titanium_ammo_box", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "df_magnum_ammo_box", qty: 1 }, { itemId: "titanium_ingot", qty: 2 }], productive: true },
  { id: "df-superalloy-ammo-box", outputId: "df_superalloy_ammo_box", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "df_titanium_ammo_box", qty: 1 }, { itemId: "titanium_alloy", qty: 1 }], productive: true },
  { id: "df-shell-set", outputId: "df_shell_set", outputQty: 1, timeSec: 1.5, facility: "assembler", inputs: [{ itemId: "copper_ingot", qty: 9 }, { itemId: "df_combustible_unit", qty: 2 }], productive: true },
  { id: "df-high-explosive-shell-set", outputId: "df_high_explosive_shell_set", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "df_explosive_unit", qty: 2 }, { itemId: "df_shell_set", qty: 1 }, { itemId: "titanium_ingot", qty: 6 }], productive: true },
  { id: "df-crystal-shell-set", outputId: "df_crystal_shell_set", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "df_crystal_explosive_unit", qty: 2 }, { itemId: "df_high_explosive_shell_set", qty: 1 }, { itemId: "titanium_alloy", qty: 3 }], productive: true },
  { id: "df-plasma-capsule", outputId: "df_plasma_capsule", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "deuterium", qty: 10 }, { itemId: "graphene", qty: 1 }, { itemId: "magnet", qty: 2 }], productive: true },
  { id: "df-antimatter-capsule", outputId: "df_antimatter_capsule", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "antimatter", qty: 10 }, { itemId: "df_plasma_capsule", qty: 1 }, { itemId: "hydrogen", qty: 10 }, { itemId: "particle_container", qty: 1 }], productive: true },
  { id: "df-missile-set", outputId: "df_missile_set", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 3 }, { itemId: "copper_ingot", qty: 6 }, { itemId: "df_combustible_unit", qty: 2 }, { itemId: "df_engine", qty: 1 }], productive: true },
  { id: "df-supersonic-missile-set", outputId: "df_supersonic_missile_set", outputQty: 2, timeSec: 4, facility: "assembler", inputs: [{ itemId: "df_explosive_unit", qty: 4 }, { itemId: "df_missile_set", qty: 2 }, { itemId: "processor", qty: 4 }, { itemId: "thruster", qty: 2 }], productive: true },
  { id: "df-gravity-missile-set", outputId: "df_gravity_missile_set", outputQty: 3, timeSec: 6, facility: "assembler", inputs: [{ itemId: "df_crystal_explosive_unit", qty: 6 }, { itemId: "df_supersonic_missile_set", qty: 3 }, { itemId: "strange_matter", qty: 3 }], productive: true },
  { id: "df-jamming-capsule", outputId: "df_jamming_capsule", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "electromagnetic_turbine", qty: 1 }, { itemId: "hydrogen", qty: 3 }, { itemId: "plasma_exciter", qty: 1 }], productive: true },
  { id: "df-suppressing-capsule", outputId: "df_suppressing_capsule", outputQty: 2, timeSec: 8, facility: "assembler", inputs: [{ itemId: "df_jamming_capsule", qty: 2 }, { itemId: "super_magnetic_ring", qty: 1 }, { itemId: "titanium_glass", qty: 2 }], productive: true },
  { id: "df-prototype", outputId: "df_prototype", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "df_engine", qty: 1 }, { itemId: "iron_ingot", qty: 3 }, { itemId: "plasma_exciter", qty: 1 }], productive: true },
  { id: "df-precision-drone", outputId: "df_precision_drone", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "df_prototype", qty: 1 }, { itemId: "electromagnetic_turbine", qty: 1 }, { itemId: "photon_combiner", qty: 2 }], productive: true },
  { id: "df-attack-drone", outputId: "df_attack_drone", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "df_prototype", qty: 1 }, { itemId: "electromagnetic_turbine", qty: 1 }, { itemId: "particle_container", qty: 1 }, { itemId: "processor", qty: 1 }], productive: true },
  { id: "df-corvette", outputId: "df_corvette", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "particle_container", qty: 3 }, { itemId: "processor", qty: 2 }, { itemId: "reinforced_thruster", qty: 1 }, { itemId: "titanium_alloy", qty: 5 }], productive: true },
  { id: "df-destroyer", outputId: "df_destroyer", outputQty: 1, timeSec: 8, facility: "assembler", inputs: [{ itemId: "frame_material", qty: 20 }, { itemId: "processor", qty: 4 }, { itemId: "reinforced_thruster", qty: 4 }, { itemId: "strange_matter", qty: 1 }], productive: true },
];
