// Generated from FactorioLab DSP data (0.10.29.21950); building recipes spot-checked through DSP 0.10.34.
import type { Item, Recipe } from "./dsp-data.ts";

export const BUILDING_SUPPORT_ITEMS: Item[] = [
  { id: "accumulator_full", name: "충전된 축전기", en: "Accumulator (full)", category: "raw", glyph: "Ac", raw: true },
  { id: "reinforced_thruster", name: "강화 추진기", en: "Reinforced Thruster", category: "component", glyph: "Re" },
  { id: "df_engine", name: "엔진", en: "Engine", category: "component", glyph: "En" },
  { id: "df_energy_shard", name: "에너지 파편", en: "Energy Shard", category: "raw", glyph: "En", raw: true },
  { id: "df_negentropy_singularity", name: "네겐트로피 특이점", en: "Negentropy Singularity", category: "raw", glyph: "Ne", raw: true },
  { id: "df_matter_recombinator", name: "물질 재조합기", en: "Matter Recombinator", category: "raw", glyph: "Ma", raw: true },
  { id: "df_dark_fog_matrix", name: "다크 포그 매트릭스", en: "Dark Fog Matrix", category: "raw", glyph: "Da", raw: true },
  { id: "df_silicon_based_neuron", name: "실리콘 기반 뉴런", en: "Silicon-based Neuron", category: "raw", glyph: "Si", raw: true },
];

export const BUILDING_ITEMS: Item[] = [
  { id: "tesla_tower", name: "테슬라 타워", en: "Tesla Tower", category: "building", glyph: "Te", building: true },
  { id: "wireless_power_tower", name: "무선 송전탑", en: "Wireless Power Tower", category: "building", glyph: "Wi", building: true },
  { id: "satellite_substation", name: "위성 배전반", en: "Satellite Substation", category: "building", glyph: "Sa", building: true },
  { id: "wind_turbine", name: "풍력 발전기", en: "Wind Turbine", category: "building", glyph: "Wi", building: true },
  { id: "thermal_power_plant", name: "화력 발전소", en: "Thermal Power Plant", category: "building", glyph: "Th", building: true },
  { id: "solar_panel", name: "태양 전지판", en: "Solar Panel", category: "building", glyph: "So", building: true },
  { id: "geothermal_power_station", name: "지열 발전소", en: "Geothermal Power Station", category: "building", glyph: "Ge", building: true },
  { id: "mini_fusion_power_plant", name: "미니 핵융합 발전소", en: "Mini Fusion Power Plant", category: "building", glyph: "Mi", building: true },
  { id: "energy_exchanger", name: "에너지 교환기", en: "Energy Exchanger", category: "building", glyph: "En", building: true },
  { id: "accumulator", name: "축전기", en: "Accumulator", category: "building", glyph: "Ac", building: true },
  { id: "ray_receiver", name: "광선 수신기", en: "Ray Receiver", category: "building", glyph: "Ra", building: true },
  { id: "artificial_star", name: "인공 항성", en: "Artificial Star", category: "building", glyph: "Ar", building: true },
  { id: "conveyor_belt_1", name: "컨베이어 벨트 Mk.I", en: "Conveyor Belt MK.I", category: "building", glyph: "Co", building: true },
  { id: "conveyor_belt_2", name: "컨베이어 벨트 Mk.II", en: "Conveyor Belt MK.II", category: "building", glyph: "Co", building: true },
  { id: "conveyor_belt_3", name: "컨베이어 벨트 Mk.III", en: "Conveyor Belt MK.III", category: "building", glyph: "Co", building: true },
  { id: "splitter", name: "분배기", en: "Splitter", category: "building", glyph: "Sp", building: true },
  { id: "automatic_piler", name: "자동 적재기", en: "Automatic Piler", category: "building", glyph: "Au", building: true },
  { id: "traffic_monitor", name: "화물 유량 모니터", en: "Traffic Monitor", category: "building", glyph: "Tr", building: true },
  { id: "spray_coater", name: "분사 도포기", en: "Spray Coater", category: "building", glyph: "Sp", building: true },
  { id: "storage_1", name: "저장고 Mk.I", en: "Depot MK.I", category: "building", glyph: "De", building: true },
  { id: "storage_2", name: "저장고 Mk.II", en: "Depot MK.II", category: "building", glyph: "De", building: true },
  { id: "storage_tank", name: "액체 저장 탱크", en: "Storage Tank", category: "building", glyph: "St", building: true },
  { id: "logistics_distributor", name: "물류 분배기", en: "Logistics Distributor", category: "building", glyph: "Lo", building: true },
  { id: "planetary_logistics_station", name: "행성 내 물류 운송소", en: "Planetary Logistics Station", category: "building", glyph: "Pl", building: true },
  { id: "interstellar_logistics_station", name: "성간 물류 운송소", en: "Interstellar Logistics Station", category: "building", glyph: "In", building: true },
  { id: "orbital_collector", name: "궤도 수집기", en: "Orbital Collector", category: "building", glyph: "Or", building: true },
  { id: "sorter_1", name: "분류기 Mk.I", en: "Sorter MK.I", category: "building", glyph: "So", building: true },
  { id: "sorter_2", name: "분류기 Mk.II", en: "Sorter MK.II", category: "building", glyph: "So", building: true },
  { id: "sorter_3", name: "분류기 Mk.III", en: "Sorter MK.III", category: "building", glyph: "So", building: true },
  { id: "sorter_4", name: "집적 분류기", en: "Pile Sorter", category: "building", glyph: "Pi", building: true },
  { id: "mining_machine", name: "채굴기", en: "Mining Machine", category: "building", glyph: "Mi", building: true },
  { id: "advanced_mining_machine", name: "대형 채굴기", en: "Advanced Mining Machine", category: "building", glyph: "Ad", building: true },
  { id: "water_pump", name: "급수 펌프", en: "Water Pump", category: "building", glyph: "Wa", building: true },
  { id: "oil_extractor", name: "원유 추출기", en: "Oil Extractor", category: "building", glyph: "Oi", building: true },
  { id: "oil_refinery", name: "정유소", en: "Oil Refinery", category: "building", glyph: "Oi", building: true },
  { id: "fractionator", name: "분별기", en: "Fractionator", category: "building", glyph: "Fr", building: true },
  { id: "chemical_plant", name: "화학 공장", en: "Chemical Plant", category: "building", glyph: "Ch", building: true },
  { id: "quantum_chemical_plant", name: "양자 화학 공장", en: "Quantum Chemical Plant", category: "building", glyph: "Qu", building: true },
  { id: "miniature_particle_collider", name: "미니 입자 충돌기", en: "Miniature Particle Collider", category: "building", glyph: "Mi", building: true },
  { id: "arc_smelter", name: "아크 제련소", en: "Arc Smelter", category: "building", glyph: "Ar", building: true },
  { id: "plane_smelter", name: "평면 제련소", en: "Plane Smelter", category: "building", glyph: "Pl", building: true },
  { id: "df_negentropy_smelter", name: "네겐트로피 제련소", en: "Negentropy Smelter", category: "building", glyph: "Ne", building: true },
  { id: "assembling_machine_1", name: "조립기 Mk.I", en: "Assembling Machine Mk.I", category: "building", glyph: "As", building: true },
  { id: "assembling_machine_2", name: "조립기 Mk.II", en: "Assembling Machine Mk.II", category: "building", glyph: "As", building: true },
  { id: "assembling_machine_3", name: "조립기 Mk.III", en: "Assembling Machine Mk.III", category: "building", glyph: "As", building: true },
  { id: "df_recomposing_assembler", name: "재구성 조립기", en: "Re-composing Assembler", category: "building", glyph: "Re", building: true },
  { id: "matrix_lab", name: "매트릭스 연구소", en: "Matrix Lab", category: "building", glyph: "Ma", building: true },
  { id: "df_self_evolution_lab", name: "자기 진화 연구소", en: "Self-evolution Lab", category: "building", glyph: "Se", building: true },
  { id: "holo_beacon", name: "홀로 비콘", en: "Holo Beacon", category: "building", glyph: "Ho", building: true },
  { id: "em_rail_ejector", name: "EM 레일건 사출기", en: "EM-Rail Ejector", category: "building", glyph: "EM", building: true },
  { id: "vertical_launching_silo", name: "수직 발사 사일로", en: "Vertical Launching Silo", category: "building", glyph: "Ve", building: true },
  { id: "df_gauss_turret", name: "가우스 포탑", en: "Gauss Turret", category: "building", glyph: "Ga", building: true },
  { id: "df_missile_turret", name: "미사일 포탑", en: "Missile Turret", category: "building", glyph: "Mi", building: true },
  { id: "df_implosion_cannon", name: "내파 대포", en: "Implosion Cannon", category: "building", glyph: "Im", building: true },
  { id: "df_laser_turret", name: "레이저 포탑", en: "Laser Turret", category: "building", glyph: "La", building: true },
  { id: "df_plasma_turret", name: "플라즈마 포탑", en: "Plasma Turret", category: "building", glyph: "Pl", building: true },
  { id: "df_plasma_turret_sr", name: "SR 플라즈마 포탑", en: "SR Plasma Turret", category: "building", glyph: "SR", building: true },
  { id: "df_battlefield_analysis_base", name: "전장 분석 기지", en: "Battlefield Analysis Base", category: "building", glyph: "Ba", building: true },
  { id: "df_jammer_tower", name: "교란 타워", en: "Jammer Tower", category: "building", glyph: "Ja", building: true },
  { id: "df_signal_tower", name: "신호 타워", en: "Signal Tower", category: "building", glyph: "Si", building: true },
  { id: "df_planetary_shield_generator", name: "행성 보호막 생성기", en: "Planetary Shield Generator", category: "building", glyph: "Pl", building: true },
];

export const BUILDING_SUPPORT_RECIPES: Recipe[] = [
  { id: "building-support-reinforced-thruster", outputId: "reinforced_thruster", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "electromagnetic_turbine", qty: 5 }, { itemId: "titanium_alloy", qty: 5 }], productive: true },
  { id: "building-support-df-engine", outputId: "df_engine", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "copper_ingot", qty: 2 }, { itemId: "magnetic_coil", qty: 1 }], productive: true },
];

export const BUILDING_RECIPES: Recipe[] = [
  { id: "building-tesla-tower", outputId: "tesla_tower", outputQty: 1, timeSec: 1, facility: "assembler", inputs: [{ itemId: "iron_ingot", qty: 2 }, { itemId: "magnetic_coil", qty: 1 }], productive: true },
  { id: "building-wireless-power-tower", outputId: "wireless_power_tower", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "plasma_exciter", qty: 3 }, { itemId: "tesla_tower", qty: 1 }], productive: true },
  { id: "building-satellite-substation", outputId: "satellite_substation", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "frame_material", qty: 2 }, { itemId: "super_magnetic_ring", qty: 10 }, { itemId: "wireless_power_tower", qty: 1 }], productive: true },
  { id: "building-wind-turbine", outputId: "wind_turbine", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "gear", qty: 1 }, { itemId: "iron_ingot", qty: 6 }, { itemId: "magnetic_coil", qty: 3 }], productive: true },
  { id: "building-thermal-power-plant", outputId: "thermal_power_plant", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "gear", qty: 4 }, { itemId: "iron_ingot", qty: 10 }, { itemId: "magnetic_coil", qty: 4 }, { itemId: "stone_brick", qty: 4 }], productive: true },
  { id: "building-solar-panel", outputId: "solar_panel", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 5 }, { itemId: "copper_ingot", qty: 10 }, { itemId: "high_purity_silicon", qty: 10 }], productive: true },
  { id: "building-geothermal-power-station", outputId: "geothermal_power_station", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "copper_ingot", qty: 20 }, { itemId: "photon_combiner", qty: 4 }, { itemId: "steel", qty: 15 }, { itemId: "super_magnetic_ring", qty: 1 }], productive: true },
  { id: "building-mini-fusion-power-plant", outputId: "mini_fusion_power_plant", outputQty: 1, timeSec: 10, facility: "assembler", inputs: [{ itemId: "carbon_nanotube", qty: 8 }, { itemId: "processor", qty: 4 }, { itemId: "super_magnetic_ring", qty: 10 }, { itemId: "titanium_alloy", qty: 12 }], productive: true },
  { id: "building-energy-exchanger", outputId: "energy_exchanger", outputQty: 1, timeSec: 15, facility: "assembler", inputs: [{ itemId: "particle_container", qty: 8 }, { itemId: "processor", qty: 40 }, { itemId: "steel", qty: 40 }, { itemId: "titanium_alloy", qty: 40 }], productive: true },
  { id: "building-accumulator", outputId: "accumulator", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "crystal_silicon", qty: 3 }, { itemId: "iron_ingot", qty: 6 }, { itemId: "super_magnetic_ring", qty: 1 }], productive: true },
  { id: "building-ray-receiver", outputId: "ray_receiver", outputQty: 1, timeSec: 8, facility: "assembler", inputs: [{ itemId: "high_purity_silicon", qty: 20 }, { itemId: "photon_combiner", qty: 10 }, { itemId: "processor", qty: 5 }, { itemId: "steel", qty: 20 }, { itemId: "super_magnetic_ring", qty: 20 }], productive: true },
  { id: "building-artificial-star", outputId: "artificial_star", outputQty: 1, timeSec: 30, facility: "assembler", inputs: [{ itemId: "annihilation_constraint_sphere", qty: 10 }, { itemId: "frame_material", qty: 20 }, { itemId: "quantum_chip", qty: 10 }, { itemId: "titanium_alloy", qty: 20 }], productive: true },
  { id: "building-conveyor-belt-1", outputId: "conveyor_belt_1", outputQty: 3, timeSec: 1, facility: "assembler", inputs: [{ itemId: "gear", qty: 1 }, { itemId: "iron_ingot", qty: 2 }], productive: true },
  { id: "building-conveyor-belt-2", outputId: "conveyor_belt_2", outputQty: 3, timeSec: 1, facility: "assembler", inputs: [{ itemId: "conveyor_belt_1", qty: 3 }, { itemId: "electromagnetic_turbine", qty: 1 }], productive: true },
  { id: "building-conveyor-belt-3", outputId: "conveyor_belt_3", outputQty: 3, timeSec: 1, facility: "assembler", inputs: [{ itemId: "conveyor_belt_2", qty: 3 }, { itemId: "graphene", qty: 1 }, { itemId: "super_magnetic_ring", qty: 1 }], productive: true },
  { id: "building-splitter", outputId: "splitter", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 1 }, { itemId: "gear", qty: 2 }, { itemId: "iron_ingot", qty: 3 }], productive: true },
  { id: "building-automatic-piler", outputId: "automatic_piler", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "gear", qty: 4 }, { itemId: "processor", qty: 2 }, { itemId: "steel", qty: 3 }, { itemId: "super_magnetic_ring", qty: 1 }], productive: true },
  { id: "building-traffic-monitor", outputId: "traffic_monitor", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "gear", qty: 2 }, { itemId: "glass", qty: 1 }, { itemId: "iron_ingot", qty: 3 }], productive: true },
  { id: "building-spray-coater", outputId: "spray_coater", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "microcrystalline_component", qty: 2 }, { itemId: "plasma_exciter", qty: 2 }, { itemId: "steel", qty: 4 }], productive: true },
  { id: "building-storage-1", outputId: "storage_1", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "iron_ingot", qty: 4 }, { itemId: "stone_brick", qty: 4 }], productive: true },
  { id: "building-storage-2", outputId: "storage_2", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "steel", qty: 8 }, { itemId: "stone_brick", qty: 8 }], productive: true },
  { id: "building-storage-tank", outputId: "storage_tank", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "glass", qty: 4 }, { itemId: "iron_ingot", qty: 8 }, { itemId: "stone_brick", qty: 4 }], productive: true },
  { id: "building-logistics-distributor", outputId: "logistics_distributor", outputQty: 1, timeSec: 8, facility: "assembler", inputs: [{ itemId: "iron_ingot", qty: 8 }, { itemId: "plasma_exciter", qty: 4 }, { itemId: "processor", qty: 4 }], productive: true },
  { id: "building-planetary-logistics-station", outputId: "planetary_logistics_station", outputQty: 1, timeSec: 20, facility: "assembler", inputs: [{ itemId: "particle_container", qty: 20 }, { itemId: "processor", qty: 40 }, { itemId: "steel", qty: 40 }, { itemId: "titanium_ingot", qty: 40 }], productive: true },
  { id: "building-interstellar-logistics-station", outputId: "interstellar_logistics_station", outputQty: 1, timeSec: 30, facility: "assembler", inputs: [{ itemId: "particle_container", qty: 20 }, { itemId: "planetary_logistics_station", qty: 1 }, { itemId: "titanium_alloy", qty: 40 }], productive: true },
  { id: "building-orbital-collector", outputId: "orbital_collector", outputQty: 1, timeSec: 30, facility: "assembler", inputs: [{ itemId: "accumulator_full", qty: 20 }, { itemId: "interstellar_logistics_station", qty: 1 }, { itemId: "reinforced_thruster", qty: 20 }, { itemId: "super_magnetic_ring", qty: 50 }], productive: true },
  { id: "building-sorter-1", outputId: "sorter_1", outputQty: 1, timeSec: 1, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 1 }, { itemId: "iron_ingot", qty: 1 }], productive: true },
  { id: "building-sorter-2", outputId: "sorter_2", outputQty: 2, timeSec: 1, facility: "assembler", inputs: [{ itemId: "electric_motor", qty: 1 }, { itemId: "sorter_1", qty: 2 }], productive: true },
  { id: "building-sorter-3", outputId: "sorter_3", outputQty: 2, timeSec: 1, facility: "assembler", inputs: [{ itemId: "electromagnetic_turbine", qty: 1 }, { itemId: "sorter_2", qty: 2 }], productive: true },
  { id: "building-sorter-4", outputId: "sorter_4", outputQty: 1, timeSec: 1, facility: "assembler", inputs: [{ itemId: "processor", qty: 1 }, { itemId: "sorter_3", qty: 2 }, { itemId: "super_magnetic_ring", qty: 1 }], productive: true },
  { id: "building-mining-machine", outputId: "mining_machine", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "gear", qty: 2 }, { itemId: "iron_ingot", qty: 4 }, { itemId: "magnetic_coil", qty: 2 }], productive: true },
  { id: "building-advanced-mining-machine", outputId: "advanced_mining_machine", outputQty: 1, timeSec: 20, facility: "assembler", inputs: [{ itemId: "frame_material", qty: 10 }, { itemId: "optical_grating_crystal", qty: 40 }, { itemId: "quantum_chip", qty: 4 }, { itemId: "super_magnetic_ring", qty: 10 }, { itemId: "titanium_alloy", qty: 20 }], productive: true },
  { id: "building-water-pump", outputId: "water_pump", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "electric_motor", qty: 4 }, { itemId: "iron_ingot", qty: 8 }, { itemId: "stone_brick", qty: 4 }], productive: true },
  { id: "building-oil-extractor", outputId: "oil_extractor", outputQty: 1, timeSec: 8, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 6 }, { itemId: "plasma_exciter", qty: 4 }, { itemId: "steel", qty: 12 }, { itemId: "stone_brick", qty: 12 }], productive: true },
  { id: "building-oil-refinery", outputId: "oil_refinery", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 6 }, { itemId: "plasma_exciter", qty: 6 }, { itemId: "steel", qty: 10 }, { itemId: "stone_brick", qty: 10 }], productive: true },
  { id: "building-fractionator", outputId: "fractionator", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "glass", qty: 4 }, { itemId: "processor", qty: 1 }, { itemId: "steel", qty: 8 }, { itemId: "stone_brick", qty: 4 }], productive: true },
  { id: "building-chemical-plant", outputId: "chemical_plant", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "glass", qty: 8 }, { itemId: "steel", qty: 8 }, { itemId: "stone_brick", qty: 8 }], productive: true },
  { id: "building-quantum-chemical-plant", outputId: "quantum_chemical_plant", outputQty: 1, timeSec: 10, facility: "assembler", inputs: [{ itemId: "chemical_plant", qty: 1 }, { itemId: "quantum_chip", qty: 3 }, { itemId: "strange_matter", qty: 3 }, { itemId: "titanium_glass", qty: 10 }], productive: true },
  { id: "building-miniature-particle-collider", outputId: "miniature_particle_collider", outputQty: 1, timeSec: 15, facility: "assembler", inputs: [{ itemId: "frame_material", qty: 20 }, { itemId: "graphene", qty: 10 }, { itemId: "processor", qty: 8 }, { itemId: "super_magnetic_ring", qty: 25 }, { itemId: "titanium_alloy", qty: 20 }], productive: true },
  { id: "building-arc-smelter", outputId: "arc_smelter", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 4 }, { itemId: "iron_ingot", qty: 4 }, { itemId: "magnetic_coil", qty: 2 }, { itemId: "stone_brick", qty: 2 }], productive: true },
  { id: "building-plane-smelter", outputId: "plane_smelter", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "arc_smelter", qty: 1 }, { itemId: "frame_material", qty: 5 }, { itemId: "plane_filter", qty: 4 }, { itemId: "unipolar_magnet", qty: 15 }], productive: true },
  { id: "building-df-negentropy-smelter", outputId: "df_negentropy_smelter", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "df_energy_shard", qty: 30 }, { itemId: "df_negentropy_singularity", qty: 10 }, { itemId: "plane_smelter", qty: 1 }, { itemId: "quantum_chip", qty: 4 }], productive: true },
  { id: "building-assembling-machine-1", outputId: "assembling_machine_1", outputQty: 1, timeSec: 2, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 4 }, { itemId: "gear", qty: 8 }, { itemId: "iron_ingot", qty: 4 }], productive: true },
  { id: "building-assembling-machine-2", outputId: "assembling_machine_2", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "assembling_machine_1", qty: 1 }, { itemId: "graphene", qty: 8 }, { itemId: "processor", qty: 4 }], productive: true },
  { id: "building-assembling-machine-3", outputId: "assembling_machine_3", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "assembling_machine_2", qty: 1 }, { itemId: "particle_broadband", qty: 8 }, { itemId: "quantum_chip", qty: 2 }], productive: true },
  { id: "building-df-recomposing-assembler", outputId: "df_recomposing_assembler", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "assembling_machine_3", qty: 1 }, { itemId: "df_energy_shard", qty: 30 }, { itemId: "df_matter_recombinator", qty: 10 }, { itemId: "quantum_chip", qty: 4 }], productive: true },
  { id: "building-matrix-lab", outputId: "matrix_lab", outputQty: 1, timeSec: 3, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 4 }, { itemId: "glass", qty: 4 }, { itemId: "iron_ingot", qty: 8 }, { itemId: "magnetic_coil", qty: 4 }], productive: true },
  { id: "building-df-self-evolution-lab", outputId: "df_self_evolution_lab", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "df_dark_fog_matrix", qty: 20 }, { itemId: "df_silicon_based_neuron", qty: 10 }, { itemId: "matrix_lab", qty: 1 }, { itemId: "quantum_chip", qty: 4 }], productive: true },
  { id: "building-holo-beacon", outputId: "holo_beacon", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "iron_ingot", qty: 3 }, { itemId: "prism", qty: 4 }, { itemId: "plasma_exciter", qty: 2 }, { itemId: "circuit_board", qty: 2 }], productive: true },
  { id: "building-em-rail-ejector", outputId: "em_rail_ejector", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "gear", qty: 20 }, { itemId: "processor", qty: 5 }, { itemId: "steel", qty: 20 }, { itemId: "super_magnetic_ring", qty: 10 }], productive: true },
  { id: "building-vertical-launching-silo", outputId: "vertical_launching_silo", outputQty: 1, timeSec: 30, facility: "assembler", inputs: [{ itemId: "frame_material", qty: 30 }, { itemId: "graviton_lens", qty: 20 }, { itemId: "quantum_chip", qty: 10 }, { itemId: "titanium_alloy", qty: 80 }], productive: true },
  { id: "building-df-gauss-turret", outputId: "df_gauss_turret", outputQty: 1, timeSec: 4, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 2 }, { itemId: "gear", qty: 8 }, { itemId: "iron_ingot", qty: 8 }, { itemId: "magnetic_coil", qty: 4 }], productive: true },
  { id: "building-df-missile-turret", outputId: "df_missile_turret", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 12 }, { itemId: "df_engine", qty: 6 }, { itemId: "electric_motor", qty: 6 }, { itemId: "steel", qty: 8 }], productive: true },
  { id: "building-df-implosion-cannon", outputId: "df_implosion_cannon", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 10 }, { itemId: "electric_motor", qty: 8 }, { itemId: "steel", qty: 10 }, { itemId: "super_magnetic_ring", qty: 2 }], productive: true },
  { id: "building-df-laser-turret", outputId: "df_laser_turret", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 6 }, { itemId: "photon_combiner", qty: 9 }, { itemId: "plasma_exciter", qty: 6 }, { itemId: "steel", qty: 9 }], productive: true },
  { id: "building-df-plasma-turret", outputId: "df_plasma_turret", outputQty: 1, timeSec: 10, facility: "assembler", inputs: [{ itemId: "plasma_exciter", qty: 5 }, { itemId: "processor", qty: 5 }, { itemId: "super_magnetic_ring", qty: 10 }, { itemId: "titanium_alloy", qty: 20 }, { itemId: "titanium_glass", qty: 10 }], productive: true },
  { id: "building-df-plasma-turret-sr", outputId: "df_plasma_turret_sr", outputQty: 1, timeSec: 8, facility: "assembler", inputs: [{ itemId: "plasma_exciter", qty: 5 }, { itemId: "processor", qty: 5 }, { itemId: "steel", qty: 15 }, { itemId: "super_magnetic_ring", qty: 5 }], productive: true },
  { id: "building-df-battlefield-analysis-base", outputId: "df_battlefield_analysis_base", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "circuit_board", qty: 18 }, { itemId: "df_engine", qty: 12 }, { itemId: "microcrystalline_component", qty: 6 }, { itemId: "steel", qty: 12 }], productive: true },
  { id: "building-df-jammer-tower", outputId: "df_jammer_tower", outputQty: 1, timeSec: 5, facility: "assembler", inputs: [{ itemId: "copper_ingot", qty: 12 }, { itemId: "diamond", qty: 6 }, { itemId: "plasma_exciter", qty: 9 }, { itemId: "processor", qty: 3 }], productive: true },
  { id: "building-df-signal-tower", outputId: "df_signal_tower", outputQty: 1, timeSec: 6, facility: "assembler", inputs: [{ itemId: "crystal_silicon", qty: 6 }, { itemId: "steel", qty: 12 }, { itemId: "wireless_power_tower", qty: 2 }], productive: true },
  { id: "building-df-planetary-shield-generator", outputId: "df_planetary_shield_generator", outputQty: 1, timeSec: 10, facility: "assembler", inputs: [{ itemId: "electromagnetic_turbine", qty: 20 }, { itemId: "particle_container", qty: 5 }, { itemId: "steel", qty: 20 }, { itemId: "super_magnetic_ring", qty: 5 }], productive: true },
];
